name: legend_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  build:
  source_gen:
  legend_annotations:
    path: ../legend_annotations/
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_test:
  build_runner: ^2.2.0